services:
  - type: web
    name: dustmon-game
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SIMULATION_MODE
        value: true
      - key: NODE_ENV
        value: production
